### ISSUE TITLE
Please don't update to FSharp.Core 6.0 when not needed :)

### ISSUE THREAD

**Issue by dsyme** [fslaborg/XPlot#170]
Libraries like this shouldn't update to FSHarp.Core 6.0 when not needed, because it then restricts where they can be used (e.g. it means they won't work in F# Interactive for VS2019 etc.)

If we do bump this kind of dependency, best to make a major version bump.

**Comment by cartermp** [comment]
I'm going to close this because the dependency on XPlot.Plotly is FSharp.Core 4.7.2: https://www.nuget.org/packages/XPlot.Plotly/

The Interactive Extension depends not only on the latest FSharp.Core, but also the latest .NET 5 (soon to be .NET 6, no doubt). It's also not a loadable component into Visual Studio 2019. I mean, someone might be able to pull it in erroneously, but any issue they have will be closed as a WONTFIX because it's not a normal package.
