### ISSUE TITLE
Google Maps charts require an API key

### ISSUE THREAD

**Issue by TahaHachana** [fslaborg/XPlot#39]

**Comment by tpetricek** [comment]
I got this too - it is very weird, because it still mostly works, but contains about missing API key. I think it needs it just to geolocate names of places. I was able to get rid of the error by first referencing Google Maps:

    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>

.. and only then referencing Google Charts.

**Comment by dsyme** [comment]
It appears it is now implemented by ``.WithApiKey`` with [this PR](https://github.com/fslaborg/XPlot/pull/47/files#diff-67672fdb5e1debcd819cf732797f075cR415)

**Comment by cartermp** [comment]
Closing as implemented.
